//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sentiment
    {
        public sentiment()
        {
            this.sentiment_sentences = new HashSet<sentiment_sentences>();
        }
    
        public int id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<decimal> average_score { get; set; }
    
        public virtual ICollection<sentiment_sentences> sentiment_sentences { get; set; }
    }
}
